FROM mcr.microsoft.com/vscode/devcontainers/python:3.12-bullseye

# Copia o requirements.txt para dentro da imagem
COPY backend/requirements.txt /tmp/requirements.txt

# Instala as dependências Python
RUN pip install -r /tmp/requirements.txt